load("@rules_cc//cc:defs.bzl", "cc_binary") # 'import' the cc_binary rule

cc_binary(
    name = "first_eg", # whatever name you want, will be name of resulting binary
                       #  BUT shoudl usually be the name of the package ('example1' in this case)
    srcs = ["main.cc"], # specify entry into program
)